module.exports = {
  roots: ['<rootDir>/__tests__'],
  collectCoverage: false,
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}'],
  coverageDirectory: 'coverage',
  preset: 'ts-jest',
  transform: {
    '^.+\\.(tsx|js|ts)$': ['ts-jest', { isolatedModules: true }],
    '^.+\\.(js|jsx)$': 'babel-jest',
    '.+\\.(png|scss|ttf)$': '<rootDir>/node_modules/jest-transform-stub',
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js', '<rootDir>/__tests__/setup.js'],
  testRegex: '(/tests/.*|(\\.|/)(test|spec))\\.tsx?$',
  moduleDirectories: ['node_modules', '<rootDir>/src'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'ttf'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@enums/(.*)$': '<rootDir>/src/enums/$1',
    '^@Routes/(.*)$': '<rootDir>/src/Routes/$1',
    '^@data/(.*)$': '<rootDir>/src/data/$1',
    '^@styles/(.*)$': '<rootDir>/src/styles/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@pages/(.*)$': '<rootDir>/src/pages/$1',
    '^@validators/(.*)$': '<rootDir>/src/validators/$1',
    '^@lib/(.*)$': '<rootDir>/src/lib/$1',
    '^@store/(.*)$': '<rootDir>/src/store/$1',
    '^@interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
  testTimeout: 30000,
};
